ktor {
  deployment {
    port = 8080
  }
}

auth {
  token = ""
}

grpc {
  port = 9090
  auth-token = ""
}

http {
  auth-token = ""
}

database {
  primary = "jdbc:postgresql://localhost:5432/punishment_service"
  username = "punishment_service"
  password = "punishment_service"
}

redis {
  node = "redis://localhost:6379"
}
