ktor {
  deployment {
    port = 8080
  }
}

grpc {
  port = 9090
}

database {
  primary = "jdbc:postgresql://localhost:5432/punishments"
  username = "punishments"
  password = "punishments"
}

redis {
  nodes = ["redis://localhost:6379"]
}
